#!/usr/bin/with-contenv bash
# https://github.com/uglymagoo/plex-claim-server

# $PLEX_CLAIM is env
CONFIG_FILE="/config/Plex Media Server/Preferences.xml"

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "Creating Preferences.xml"

  TMP_FILE="$(mktemp)"
  cat <<EOF >"$TMP_FILE"
<?xml version="1.0" encoding="utf-8"?>
<Preferences/>
EOF

  install -dm755 -o $PUID -g $PGID "$(dirname "$CONFIG_FILE")"
  install -m600  -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
fi


function getPref {
  local key="$1"

  sed -n -E "s/^.*${key}=\"([^\"]*)\".*$/\1/p" "$CONFIG_FILE"
}

function setPref {
  local key="$1"
  local value="$2"

  count="$(grep -c "${key}" "$CONFIG_FILE")"
  count=$(($count + 0))

  if [[ $count > 0 ]]; then
    sed -i -E "s/${key}=\"([^\"]*)\"/${key}=\"$value\"/" "$CONFIG_FILE"
  else
    sed -i -E "s/\/>/ ${key}=\"$value\"\/>/" "$CONFIG_FILE"
  fi
}

# servers client identifier
serial="$(getPref "MachineIdentifier")"
if [[ -z "$serial" ]]; then
  serial="$(uuidgen)"
  setPref "MachineIdentifier" "$serial"
fi
clientId="$(getPref "ProcessedMachineIdentifier")"
if [[ -z "$clientId" ]]; then
  clientId="$(echo -n "${serial}- Plex Media Server" | sha1sum | cut -b 1-40)"
  setPref "ProcessedMachineIdentifier" "$clientId"
fi

# get server token and only turn claim token into server token if we have former but not latter
token="$(getPref "PlexOnlineToken")"
if [[ -n "$PLEX_CLAIM" && -z "$token" ]]; then
  echo "Attempting to obtain server token from claim token"

  response="$(curl -sSf -X POST \
    -H 'X-Plex-Client-Identifier: '$clientId \
    -H 'X-Plex-Product: Plex Media Server'\
    -H 'X-Plex-Version: 1.1' \
    -H 'X-Plex-Provides: server' \
    -H 'X-Plex-Platform: Linux' \
    -H 'X-Plex-Platform-Version: 1.0' \
    -H 'X-Plex-Device-Name: PlexMediaServer' \
    -H 'X-Plex-Device: Linux' \
    "https://plex.tv/api/claim/exchange?token=$PLEX_CLAIM")"
  token="$(echo "$response" | sed -n 's/.*<authentication-token>\(.*\)<\/authentication-token>.*/\1/p')"

  if [[ -n "$token" ]]; then
    echo "Plex Media Server successfully claimed"

    setPref "PlexOnlineToken" "$token"
  fi
fi
