#!/usr/bin/with-contenv bash

LOG_FILE="/config/Plex Media Server/Logs/Plex Media Server.log"

# create initial log file
if [[ ! -f "$LOG_FILE" ]]; then
  install -dm755 -o $PUID -g $PGID \
    "/config/Plex Media Server" \
    "/config/Plex Media Server/Logs"

  install -m600 -o $PUID -g $PGID /dev/null "$LOG_FILE"
fi

# listen for logs
exec tail -F -n0 "$LOG_FILE"
